# Generated by Django 5.2 on 2025-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transtorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('drescicao_tratamento', models.TextField(max_length=500)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
    ]
