# Generated by Django 5.2 on 2025-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteser', '0002_rename_drescicao_tratamento_transtorno_descricao_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
    ]
